CREATE DATABASE IF NOT EXISTS rutadocente CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rutadocente;
CREATE TABLE roles(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) NOT NULL UNIQUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE subjects(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL UNIQUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE tabulator_groups(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE tabulator_subgroups(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,group_id INT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(group_id) REFERENCES tabulator_groups(id) ON DELETE CASCADE);
CREATE TABLE users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,first_name VARCHAR(80) NOT NULL,last_name VARCHAR(80) NOT NULL,email VARCHAR(160) NOT NULL UNIQUE,phone VARCHAR(30),avatar_path VARCHAR(255) NULL,role_id INT UNSIGNED NOT NULL,subject_id INT UNSIGNED NULL,password VARCHAR(255) NOT NULL,test_enabled TINYINT(1) DEFAULT 0,tabulator_enabled TINYINT(1) DEFAULT 0,active TINYINT(1) DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(role_id) REFERENCES roles(id),FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE SET NULL);
CREATE TABLE resources(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,type ENUM('test','tabulador') NOT NULL,name VARCHAR(160) NOT NULL,description TEXT,subject_id INT UNSIGNED NULL,group_id INT UNSIGNED NULL,subgroup_id INT UNSIGNED NULL,file_path VARCHAR(255),external_link VARCHAR(500),active TINYINT(1) DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE SET NULL,FOREIGN KEY(group_id) REFERENCES tabulator_groups(id) ON DELETE SET NULL,FOREIGN KEY(subgroup_id) REFERENCES tabulator_subgroups(id) ON DELETE SET NULL);
INSERT INTO roles(name) VALUES('administrador'),('docente');
INSERT INTO subjects(name) VALUES('Educación Parvularia'),('Matemática'),('Historia'),('Inglés'),('Lenguaje'),('Ciencias');
INSERT INTO tabulator_groups(name) VALUES('Evaluación diagnóstica'),('Evaluación formativa');
INSERT INTO tabulator_subgroups(group_id,name) VALUES(1,'Inicio de año'),(2,'Seguimiento mensual');
-- Acceso inicial: admin@rutadocente.cl / password. Cambiar inmediatamente.
INSERT INTO users(first_name,last_name,email,phone,role_id,password,active) VALUES('Administrador','Ruta Docente','admin@rutadocente.cl','+56 9 7577 8434',1,'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',1);
-- Docente demo: docente@rutadocente.cl / password
INSERT INTO users(first_name,last_name,email,phone,role_id,subject_id,password,test_enabled,tabulator_enabled,active) VALUES('Docente','Demostración','docente@rutadocente.cl','+56 9 0000 0000',2,2,'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',1,1,1);
INSERT INTO resources(type,name,description,subject_id,external_link) VALUES('test','Diagnóstico de Matemática','Test inicial asociado a la asignatura de Matemática.',2,'https://rutadocente.com/'),('tabulador','Tabulador de resultados','Plantilla para registrar y visualizar avances.',2,'https://rutadocente.com/');
