<?php
namespace App\Controllers;
use App\Core\Controller;
use App\Core\Database;
use App\Models\{User,Resource};

class TeacherController extends Controller {
 function dashboard():void{$u=$this->teacher();$tests=$u['test_enabled']?(new Resource)->visibleFor($u,'test'):[];$tabs=$u['tabulator_enabled']?(new Resource)->visibleFor($u,'tabulador'):[];$this->view('teacher/dashboard',['title'=>'Área docente','user'=>$u,'tests'=>$tests,'tabulators'=>$tabs]);}
 function tests():void{$u=$this->teacher();$items=$u['test_enabled']?(new Resource)->visibleFor($u,'test'):[];$this->view('teacher/tests',['title'=>'Mis tests','user'=>$u,'items'=>$items,'enabled'=>(bool)$u['test_enabled']]);}
 function tabulators():void{$u=$this->teacher();$items=$u['tabulator_enabled']?(new Resource)->visibleFor($u,'tabulador'):[];$this->view('teacher/tabulators',['title'=>'Mis talleres asincrónicos','user'=>$u,'items'=>$items,'enabled'=>(bool)$u['tabulator_enabled']]);}
 function profile():void{$sessionUser=$this->teacher();$this->ensureAvatarColumn();$u=(new User)->findDetailed((int)$sessionUser['id'])??$sessionUser;$_SESSION['user']=$u;$this->view('teacher/profile',['title'=>'Mi perfil','user'=>$u]);}
 function update():void{$u=$this->teacher();verify_csrf();$this->ensureAvatarColumn();$avatar=null;if(!empty($_FILES['avatar']['name'])){$avatar=$this->storeAvatar($_FILES['avatar']);if(!empty($u['avatar_path'])){$old=config('upload_dir').'/'.ltrim($u['avatar_path'],'/');if(is_file($old))@unlink($old);}}(new User)->updateProfile((int)$u['id'],$_POST,$avatar);$fresh=(new User)->findDetailed((int)$u['id']);if($fresh)$_SESSION['user']=$fresh;flash('success','Perfil actualizado correctamente.');redirect('/docente/perfil');}
 function photo():void{$u=$this->teacher();$this->ensureAvatarColumn();$fresh=(new User)->findDetailed((int)$u['id']);$relative=$fresh['avatar_path']??'';$file=config('upload_dir').'/'.ltrim($relative,'/');if(!$relative||!is_file($file)){http_response_code(404);exit;}$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($file);if(!in_array($mime,['image/jpeg','image/png','image/webp'],true)){http_response_code(415);exit;}header('Content-Type: '.$mime);header('Content-Length: '.filesize($file));header('Cache-Control: private, max-age=3600');readfile($file);exit;}
 function download():void{$u=$this->teacher();$r=(new Resource)->find((int)($_GET['id']??0));if(!$r||!$r['active']||($r['subject_id']&&$r['subject_id']!=$u['subject_id'])||($r['type']==='test'&&!$u['test_enabled'])||($r['type']==='tabulador'&&!$u['tabulator_enabled'])){http_response_code(403);exit('Acceso denegado');}$file=config('upload_dir').'/'.basename($r['file_path']??'');if(!is_file($file)){http_response_code(404);exit('Archivo no encontrado');}header('Content-Type: application/octet-stream');header('Content-Disposition: attachment; filename="'.preg_replace('/[^a-zA-Z0-9._-]/','_',basename($r['name'])).'.'.pathinfo($file,PATHINFO_EXTENSION).'"');header('Content-Length: '.filesize($file));readfile($file);exit;}
 private function ensureAvatarColumn():void{$db=Database::connection();$exists=$db->query("SHOW COLUMNS FROM users LIKE 'avatar_path'")->fetch();if(!$exists)$db->exec('ALTER TABLE users ADD COLUMN avatar_path VARCHAR(255) NULL AFTER phone');}
 private function storeAvatar(array $file):string{if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)exit('No se pudo subir la imagen');if(($file['size']??0)>3*1048576)exit('La foto no puede superar 3 MB');$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$extensions=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($extensions[$mime]))exit('Formato de imagen no permitido');$relative='avatars/'.bin2hex(random_bytes(16)).'.'.$extensions[$mime];$directory=config('upload_dir').'/avatars';if(!is_dir($directory))mkdir($directory,0755,true);if(!move_uploaded_file($file['tmp_name'],config('upload_dir').'/'.$relative))exit('No se pudo guardar la imagen');return $relative;}
}
