<!doctype html>
<html lang="es">
<head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width,initial-scale=1">
 <meta name="description" content="Tests y evaluaciones para fortalecer la preparación docente 2026">
 <title>Tests | Ruta Docente 2026</title>
 <link rel="stylesheet" href="<?=url('/assets/css/site.css')?>">
 <link rel="icon" href="<?=url('/assets/img/logo-ruta-docente.png')?>">
</head>
<body class="tests-public-page">
<div class="topbar"><div class="container"><span>Apoyo docente para todo Chile</span><div><a href="mailto:aulaentretenida0@gmail.com">✉ aulaentretenida0@gmail.com</a><a href="tel:+56975778434">☎ +56 9 7577 8434</a></div></div></div>
<header><div class="container header-inner"><a class="brand" href="<?=url('/')?>"><img src="<?=url('/assets/img/logo-ruta-docente.png')?>" alt="Logo Ruta Docente"><div><strong>Ruta Docente</strong><small>Portafolio Docente 2026</small></div></a><button class="menu" aria-label="Abrir menú" aria-expanded="false">☰</button><nav><a href="<?=url('/')?>">Inicio</a><a href="<?=url('/asignaturas')?>">Asignaturas</a><a href="<?=url('/portafolio')?>">Portafolio</a><a href="<?=url('/clases-asincronicas')?>">Clases asincrónicas</a><a class="active" href="<?=url('/tests')?>">Test</a><a href="<?=url('/tabuladores')?>">Tabuladores</a><a href="<?=url('/recursos')?>">Recursos</a><a href="<?=url('/contacto')?>">Contacto</a><a href="<?=url('/preguntas-frecuentes')?>">Preguntas frecuentes</a></nav><a class="pill header-cta" href="<?=url('/login')?>">Acceso docente</a></div></header>

<main>
 <section class="tests-page-hero">
  <div class="container tests-hero-grid">
   <div><span class="eyebrow pale">TESTS RUTA DOCENTE</span><h1>Practica, mide y fortalece tu preparación.</h1><p>Evaluaciones organizadas por asignatura para reconocer avances, reforzar contenidos y llegar con mayor seguridad a cada desafío docente.</p><div class="actions"><a class="btn test-gold-button" href="<?=url('/login')?>">Acceder a mis tests →</a><a class="text-link test-light-link" href="#contenido">Conocer cómo funcionan ↓</a></div><div class="tests-hero-stats"><div><b>24/7</b><span>Acceso desde cualquier dispositivo</span></div><div><b>100%</b><span>Contenido práctico y organizado</span></div><div><b>2026</b><span>Preparación docente actualizada</span></div></div></div>
   <div class="tests-hero-image"><img src="https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&w=1200&q=85" alt="Persona respondiendo un test escrito"><span><b>✓</b> Aprende a tu ritmo</span></div>
  </div>
 </section>

 <section class="section tests-benefits" id="contenido"><div class="container"><div class="section-head"><div><span class="eyebrow">PREPARACIÓN CON PROPÓSITO</span><h2>Tests que convierten la práctica en progreso.</h2></div><p>Cada evaluación ayuda a detectar fortalezas, reconocer contenidos por reforzar y orientar mejor tu estudio sin perder tiempo.</p></div><div class="cards"><article class="card"><span class="icon">✓</span><small>01 · DIAGNÓSTICO</small><h3>Conoce tu punto de partida</h3><p>Identifica conocimientos consolidados y áreas que requieren mayor atención.</p><a href="<?=url('/login')?>">Comenzar preparación →</a></article><article class="card"><span class="icon">◎</span><small>02 · ASIGNATURAS</small><h3>Contenido organizado</h3><p>Accede a tests relacionados con tu asignatura y perfil docente.</p><a href="<?=url('/login')?>">Ver mis recursos →</a></article><article class="card"><span class="icon">↗</span><small>03 · PROGRESO</small><h3>Practica a tu ritmo</h3><p>Repite actividades y fortalece gradualmente tu nivel de preparación.</p><a href="<?=url('/login')?>">Ingresar al área docente →</a></article><article class="card"><span class="icon">▦</span><small>04 · RECURSOS</small><h3>Material complementario</h3><p>Combina evaluaciones con guías, orientaciones y recursos descargables.</p><a href="<?=url('/recursos')?>">Explorar recursos →</a></article></div></div></section>

 <section class="split-section tests-process"><div class="container tests-process-grid"><div class="tests-process-photo"><img src="https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1100&q=85" alt="Persona estudiando y preparando una evaluación"><span>PREPARACIÓN<br><b>PASO A PASO</b></span></div><div><span class="eyebrow">UNA RUTA SIMPLE</span><h2>De la evaluación a una preparación más clara.</h2><p class="lead">El espacio docente reúne tus tests en un solo lugar y muestra únicamente los contenidos habilitados para tu asignatura.</p><ol class="tests-steps"><li><span>01</span><div><h3>Ingresa a tu cuenta</h3><p>Accede de forma segura a tu área docente personal.</p></div></li><li><span>02</span><div><h3>Elige un test</h3><p>Busca la evaluación que quieres practicar o descargar.</p></div></li><li><span>03</span><div><h3>Refuerza tus aprendizajes</h3><p>Usa cada resultado para orientar tu siguiente etapa de estudio.</p></div></li></ol><a class="btn" href="<?=url('/login')?>">Ir a mis tests →</a></div></div></section>

 <section class="section tests-gallery-section"><div class="container"><div class="section-title center"><span class="eyebrow">APRENDER · PRACTICAR · AVANZAR</span><h2>Una experiencia enfocada en tu crecimiento.</h2><p>Preparación flexible, recursos claros y evaluaciones disponibles cuando las necesites.</p></div><div class="tests-gallery"><img loading="lazy" src="https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=900&q=85" alt="Cuaderno preparado para responder un test"><img loading="lazy" src="https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=85" alt="Docente guiando una evaluación en aula"><img loading="lazy" src="https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=900&q=85" alt="Estudiante concentrada en una actividad evaluativa"><img loading="lazy" src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=85" alt="Grupo preparando una evaluación"><img loading="lazy" src="https://images.unsplash.com/photo-1571260899304-425eee4c7efc?auto=format&fit=crop&w=900&q=85" alt="Docente revisando material de evaluación"></div></div></section>

 <section class="cta tests-cta"><div class="container cta-inner"><div><span class="eyebrow pale">TU PRÓXIMO PASO</span><h2>Prepárate con mayor confianza.</h2><p>Ingresa a tu espacio docente y revisa los tests disponibles para tu asignatura.</p></div><a class="btn white" href="<?=url('/login')?>">Acceder a mis tests →</a></div></section>
</main>

<a class="whatsapp" href="https://wa.me/56975778434" aria-label="WhatsApp">◉</a>
<footer><div class="container footer-grid"><div><a class="brand light" href="<?=url('/')?>"><img src="<?=url('/assets/img/logo-ruta-docente.png')?>" alt="Ruta Docente"><div><strong>Ruta Docente</strong><small>Enseñar, avanzar, transformar.</small></div></a><p>Recursos claros y acompañamiento cercano para fortalecer tu práctica, tu portafolio y el aprendizaje de tus estudiantes.</p></div><div><h3>Explora</h3><a href="<?=url('/asignaturas')?>">Asignaturas</a><a href="<?=url('/portafolio')?>">Portafolio</a><a href="<?=url('/clases-asincronicas')?>">Clases asincrónicas</a><a href="<?=url('/tests')?>">Test</a></div><div><h3>Ayuda</h3><a href="<?=url('/recursos')?>">Recursos</a><a href="<?=url('/preguntas-frecuentes')?>">Preguntas frecuentes</a><a href="<?=url('/contacto')?>">Contacto</a></div><div><h3>Conversemos</h3><a href="mailto:aulaentretenida0@gmail.com">aulaentretenida0@gmail.com</a><a href="tel:+56975778434">+56 9 7577 8434</a><a href="https://www.facebook.com/AulaEntretenida">Facebook · Aula Entretenida</a></div></div><div class="container copyright"><span>© 2026 Ruta Docente. Todos los derechos reservados.</span><span>Hecho con dedicación para docentes de Chile 🇨🇱</span></div></footer>
<script src="<?=url('/assets/js/site-public.js')?>"></script>
</body>
</html>
